# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:latest

pipelines:
  branches:
    staging:
      - step:
          name: Deploy to TEST
          deployment: TEST
          script:
            - ssh testcoachscom@test.coachsome.com 'bash -s' < ./deploy-test.sh
            - echo "Deploy completed successfully on client Test Server"
 